### ISSUE TITLE
分页是怎么实现的？

### ISSUE THREAD

**Issue by zhenzi0322** [ydtg1993/laravel-admin-expand-table#2]
我使用了该组件，但是分页不了

**Comment by ydtg1993** [comment]
你检查自己的接口了么 post接收参数p:当前页数 limit:每页条目数

**Comment by zhenzi0322** [comment]
> 你检查自己的接口了么 post接收参数p:当前页数 limit:每页条目数

我已经解决了，我之前一直是用GET请求，后来改成POST请求就可以了

**Comment by zhenzi0322** [comment]
只能查看表格数据？没有相关操作的嘛

**Comment by zhenzi0322** [comment]
> 你检查自己的接口了么 post接收参数p:当前页数 limit:每页条目数

没有相关的一些操作的嘛，就比如我选中第一列就取到ID相关信息之类的

**Comment by ydtg1993** [comment]
那你只有改改js了 这其实就是个很简单的js前端 自定义需要自己动手啰
